"""Изменил тип поля перечисления в моделях тарнзакций и сервисов.

Revision ID: 10dca6ce408b
Revises: 8b383dad9a04
Create Date: 2024-12-14 17:51:02.185091
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10dca6ce408b'
down_revision: Union[str, None] = '8b383dad9a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
transaction_type = sa.Enum(
    'SALE', 'PURCHASE', name='transactiontype', create_constraint=True
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column(
            'service_type',
            existing_type=sa.VARCHAR(),
            type_=transaction_type,
            existing_nullable=False,
            postgresql_using='service_type::transactiontype',
        )

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column(
            'transaction_type',
            existing_type=sa.VARCHAR(),
            type_=transaction_type,
            existing_nullable=False,
            postgresql_using='transaction_type::transactiontype',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column(
            'transaction_type',
            existing_type=transaction_type,
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column(
            'service_type',
            existing_type=transaction_type,
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
