"""empty message

Revision ID: 23c5fcfd41f1
Revises: 53a88cbc36bd
Create Date: 2024-11-22 15:07:15.957620
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23c5fcfd41f1'
down_revision: Union[str, None] = '53a88cbc36bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('currency', schema=None) as batch_op:
		batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
		batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

	with op.batch_alter_table('riskminimisation', schema=None) as batch_op:
		batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
		batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

	with op.batch_alter_table('transaction', schema=None) as batch_op:
		batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
		batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('transaction', schema=None) as batch_op:
		batch_op.drop_constraint(None, type_='foreignkey')
		batch_op.drop_column('user_id')

	with op.batch_alter_table('riskminimisation', schema=None) as batch_op:
		batch_op.drop_constraint(None, type_='foreignkey')
		batch_op.drop_column('user_id')

	with op.batch_alter_table('currency', schema=None) as batch_op:
		batch_op.drop_constraint(None, type_='foreignkey')
		batch_op.drop_column('user_id')

	# ### end Alembic commands ###
