"""Добавил в прибыть значение по-умолчанию

Revision ID: 3920e885f5b1
Revises: 0929fde640b3
Create Date: 2024-12-04 14:56:04.307318
"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '3920e885f5b1'
down_revision: Union[str, None] = '0929fde640b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
