"""Реализовал таблицу для кеширования данных с CoinMarketCap

Revision ID: ca7d2a0ea694
Revises: 2ed69396d73d
Create Date: 2025-01-28 21:34:34.707880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7d2a0ea694'
down_revision: Union[str, None] = '2ed69396d73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmcdata',
    sa.Column('cmc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('cmc_rank', sa.Integer(), nullable=False),
    sa.Column('circulating_supply', sa.BigInteger(), nullable=False),
    sa.Column('total_supply', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('percent_change_24h', sa.Float(), nullable=False),
    sa.Column('percent_change_7d', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cmcdata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cmcdata_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmcdata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cmcdata_id'))

    op.drop_table('cmcdata')
    # ### end Alembic commands ###
