"""Убрал автодобавление даты создания для транзакции.

Revision ID: d4f7928f0a27
Revises: 10dca6ce408b
Create Date: 2025-01-02 01:32:10.996551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f7928f0a27'
down_revision: Union[str, None] = '10dca6ce408b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=False,
            existing_server_default=sa.text('now()'),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=False,
            existing_server_default=sa.text('now()'),
        )

    # ### end Alembic commands ###
